### ISSUE TITLE
Use different numbers for TODO, FIXME and XXX

### ISSUE THREAD

**Issue by aelgru** [schlamar/flake8-todo#4]
Using different numbers for TODO, FIXME and XXX would be nice.

```
T000 - TODO note found.
T001 - FIXME note found.
T002 - XXX note found.
```

**Comment by danpalmer** [comment]
@aelgru any reason for closing this? I'd quite like this, happy to open a PR if you're likely to merge it.

**Comment by tommilligan** [comment]
@aelgru would also be interested in this - I'd like to fail my build on `FIXME`s, but not on `TODO`s. Will write up a PR

**Comment by tommilligan** [comment]
@danpalmer I've released a fork called `flake8-fixme` which implements this. You can give it a try [here](https://github.com/tommilligan/flake8-fixme).
