### ISSUE TITLE
needs release with PR#6

### ISSUE THREAD

**Issue by AnneGilles** [schlamar/flake8-todo#7]
flake8-todo is part of plone/plone.recipe.codeanalysis, esp. the 'recommended' part.
I just experienced a lot of test failures, as flake8-todo is unable to import pep8, which is not declared as a dependency. 

and hey, pycodestyle is the new pep8

see schlamar/flake8-todo/pull/6

**Comment by schlamar** [comment]
Should be fixed now, please give feedback. Thanks.

**Comment by AnneGilles** [comment]
Works. Thank You!
