### ISSUE TITLE
We already have: pycodestyle 2.1.0 but flake8-todo 0.6 requires 'pycodestyle<2.1.0,>=2.0.0'

### ISSUE THREAD

**Issue by idgserpro** [schlamar/flake8-todo#9]
After the [new version 2.1.0 of pycodestyle](https://github.com/PyCQA/pycodestyle/blob/020d6ff6a85c237b0bdaa4c50625e6385dcddc16/CHANGES.txt#L4), the installation started to present the error below:

```bash
Got pycodestyle 2.1.0.
Version and requirements information containing pycodestyle:
  Requirement of flake8>=2.0.0: pycodestyle<2.2.0,>=2.0.0
  Requirement of flake8-todo: pycodestyle<2.1.0,>=2.0.0
  Requirement of flake8>=2.4.0: pycodestyle<2.2.0,>=2.0.0
While:
  Installing code-analysis.
Error: There is a version conflict.
We already have: pycodestyle 2.1.0
but flake8-todo 0.6 requires 'pycodestyle<2.1.0,>=2.0.0'.
```

Is [this pinning](https://github.com/schlamar/flake8-todo/blob/dd1862db44e356e1946828799026a7a89b837f04/setup.py#L34) still needed?

**Comment by schlamar** [comment]
Should be fixed in 0.7.
